/***************************************************************************//**
 * @file tarang_ai.h
 * @brief TARANG AI inference module — C-compatible public API.
 *
 * Wraps TFLite Micro interpreter management for the two-model cascade:
 *   - Gate CNN  (~40KB tflite, ~8KB tensor arena)
 *   - SV Head CNN (~32KB tflite, ~12KB tensor arena)
 *
 * Models loaded from gate_model_data[] and sv_model_data[] (const arrays
 * in flash, generated by xxd from the .tflite files).
 *
 * RR feature scaling uses rr_scaler.h (mean/scale arrays from training).
 *
 * This file is C-compatible (extern "C"). The implementation in tarang_ai.cc
 * is C++ because TFLite Micro is a C++ library.
 *
 * Target : EFR32MG26B510F3200IM48 (Series 2, Cortex-M33 + MVP)
 ******************************************************************************/
#ifndef TARANG_AI_H
#define TARANG_AI_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
 * Initialization
 ******************************************************************************/

/***************************************************************************//**
 * @brief Initialize both TFLite Micro interpreters (Gate + SV Head).
 *
 * Must be called ONCE at boot, after sl_system_init() but before the main loop.
 * Allocates tensor arenas from static buffers (no heap).
 *
 * Validates input tensor shapes:
 *   - ecg_input: [1, 130] int8
 *   - rr_input:  [1, 4]   int8
 *
 * @return true if both models loaded and validated successfully.
 ******************************************************************************/
bool tarang_ai_init(void);

/*******************************************************************************
 * Inference — Tier 1: Gate CNN
 ******************************************************************************/

/***************************************************************************//**
 * @brief Run Gate CNN inference.
 *
 * Input:  130-sample ECG beat window (float, post-DSP z-score normalized)
 *         + 4 RR features (float, raw ms/bpm — scaling applied internally)
 *
 * Output: P(abnormal) as float [0.0, 1.0].
 *         If > TARANG_GATE_THRESHOLD → beat is suspicious, run SV Head.
 *         If ≤ TARANG_GATE_THRESHOLD → classify as N, skip SV Head.
 *
 * @param[in] ecg_window  130 float samples (65 pre-R + 65 post-R, R at idx 65)
 * @param[in] rr_features 4 floats: [rr_prev_ms, rr_mean_5_ms, rr_std_5_ms, local_hr_bpm]
 * @return P(abnormal) in [0.0, 1.0], or -1.0f on error.
 ******************************************************************************/
float tarang_ai_gate_predict(const float *ecg_window, const float *rr_features);

/*******************************************************************************
 * Inference — Tier 2: SV Head CNN
 ******************************************************************************/

/***************************************************************************//**
 * @brief Run SV Head CNN inference.
 *
 * Input:  Same 130-sample window + 4 RR features as Gate.
 * Output: P(V) and P(S) via pointers — two independent sigmoids.
 *
 * Classification logic (caller's responsibility):
 *   if P(V) > V_THR → V (PVC)
 *   elif P(S) > S_THR → S (PAC)
 *   else → N (gate was wrong, happens occasionally, not an error)
 *
 * @param[in]  ecg_window  130 float samples
 * @param[in]  rr_features 4 floats
 * @param[out] p_v         P(Ventricular) in [0.0, 1.0]
 * @param[out] p_s         P(Supraventricular) in [0.0, 1.0]
 * @return true on success, false on inference error.
 ******************************************************************************/
bool tarang_ai_sv_predict(const float *ecg_window, const float *rr_features,
                           float *p_v, float *p_s);

/*******************************************************************************
 * Status / Diagnostics
 ******************************************************************************/

/***************************************************************************//**
 * @brief Check if AI module initialized successfully.
 * @return true if both models are loaded and ready.
 ******************************************************************************/
bool tarang_ai_is_ready(void);

/***************************************************************************//**
 * @brief Get the Gate CNN model size in bytes (flash footprint).
 ******************************************************************************/
uint32_t tarang_ai_gate_model_size(void);

/***************************************************************************//**
 * @brief Get the SV Head CNN model size in bytes (flash footprint).
 ******************************************************************************/
uint32_t tarang_ai_sv_model_size(void);

/***************************************************************************//**
 * @brief Get the Gate CNN tensor arena size in bytes (RAM footprint).
 ******************************************************************************/
uint32_t tarang_ai_gate_arena_size(void);

/***************************************************************************//**
 * @brief Get the SV Head CNN tensor arena size in bytes (RAM footprint).
 ******************************************************************************/
uint32_t tarang_ai_sv_arena_size(void);

#ifdef __cplusplus
}
#endif

#endif /* TARANG_AI_H */
